version: '3'

networks:
  monet_network:
    external: true

volumes:
  kafka-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/kafka/data
      o: bind
  kafka-logs:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/kafka/logs
      o: bind

services:
  kafka:
    restart: always
    privileged: true
    image: registry.cn-beijing.aliyuncs.com/monet/kafka:3.6.1
    container_name: kafka
    environment:
      TZ: Asia/Shanghai
      BITNAMI_DEBUG: 'true'
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://127.0.0.1:19093,CLIENT://127.0.0.1:19092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_HEAP_OPTS: '-Xmx512m -Xms512m'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT'
      KAFKA_CFG_LISTENERS: 'INTERNAL://:9093,CLIENT://:9092'
      KAFKA_ZOOKEEPER_PROTOCOL: PLAINTEXT
      KAFKA_VOLUME_DIR: /bitnami/kafka
      KAFKA_LOG_DIR: /opt/bitnami/kafka/logs
      KAFKA_CFG_DELETE_TOPIC_ENABLE: 'false'
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES: '10000'
      KAFKA_CFG_LOG_FLUSH_INTERVAL_MS: '1000'
      KAFKA_CFG_LOG_RETENTION_BYTES: '1073741824'
      KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS: '300000'
      KAFKA_CFG_LOG_RETENTION_HOURS: '168'
      KAFKA_CFG_MESSAGE_MAX_BYTES: '1000012'
      KAFKA_CFG_LOG_SEGMENT_BYTES: '1073741824'
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: '1'
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_CFG_NUM_IO_THREADS: '8'
      KAFKA_CFG_NUM_NETWORK_THREADS: '3'
      KAFKA_CFG_NUM_PARTITIONS: '1'
      KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR: '1'
      KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES: '102400'
      KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES: '104857600'
      KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES: '102400'
      KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS: '6000'
      KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
      KAFKA_CFG_SUPER_USERS: 'User:admin'
    volumes:
      - kafka-data:/bitnami/kafka
      - kafka-logs:/opt/bitnami/kafka/logs
    logging:
      driver: 'json-file'
      options:
        max-size: '500m'
        max-file: "10"
    ports:
      - "19092:9092"
      - "19093:9093"
    networks:
      - monet_network

