version: '3'

networks:
  monet_network:
    external: true

volumes:
  elasticsearch-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/elasticsearch/data
      o: bind
  elasticsearch-plugins:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/elasticsearch/plugins
      o: bind
  elasticsearch-config:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/elasticsearch/config
      o: bind
  elasticsearch-logs:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/elasticsearch/logs
      o: bind

services:
  elasticsearch:
    restart: always
    privileged: true
    image: registry.cn-beijing.aliyuncs.com/monet/elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      ELASTIC_PASSWORD_FILE: /run/secrets/elasticsearch_password
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-plugins:/usr/share/elasticsearch/plugins
      - elasticsearch-config:/usr/share/elasticsearch/config
      - elasticsearch-logs:/usr/share/elasticsearch/logs
    secrets:
      - elasticsearch_password
    logging:
      driver: 'json-file'
      options:
        max-size: '500m'
        max-file: "10"
    ports:
      - "19200:9200"
      - "19300:9300"
    networks:
      - monet_network

secrets:
  elasticsearch_password:
    file: /opt/docker/secrets/elasticsearch_password.txt