version: '3'

networks:
  monet_network:
    external: true

volumes:
  nacos-logs:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/nacos/logs
      o: bind

services:
  nacos:
    restart: always
    privileged: true
    image: registry.cn-beijing.aliyuncs.com/monet/nacos-server:v2.2.3
    container_name: nacos
    environment:
      TZ: Asia/Shanghai
      MODE: standalone
      NACOS_AUTH_ENABLE: true
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: LZ4N4jUFbg5C
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      JVM_XMS: 512m
      JVM_MMX: 512m
      JVM_XMN: 256m
      NACOS_AUTH_TOKEN: MmE4MGI5NmQ3Yzc5Yjg5Y2YzM2Y0ODU1M2FiYmEzYzQ=
      NACOS_AUTH_IDENTITY_KEY: nacos
      NACOS_AUTH_IDENTITY_VALUE: LZ4N4jUFbg5C
    volumes:
      - nacos-logs:/home/nacos/logs
    logging:
      driver: 'json-file'
      options:
        max-size: '500m'
        max-file: "10"
    ports:
      - "18848:8848"
      - "17848:7848"
      - "19848:9848"
    networks:
      - monet_network

