version: '3'

networks:
  monet_network:
    external: true
    
volumes:
  skywalking-message:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/skywalking/message
      o: bind
  skywalking-config:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/skywalking/config
      o: bind
  skywalking-logs:
    driver: local
    driver_opts:
      type: none
      device: /opt/docker/skywalking/logs
      o: bind
    
services:
  skywalking-oap:
    restart: always
    privileged: true
    image: registry.cn-beijing.aliyuncs.com/monet/skywalking-oap-server:9.6.0
    container_name: skywalking-oap-server
    environment:
      TZ: Asia/Shanghai
      SW_NAMESPACE: skywalking
      SW_STORAGE: elasticsearch
      SW_ES_USER: elastic
      SW_ES_PASSWORD: 'LZ4N4jUFbg5C'
      SW_STORAGE_ES_CLUSTER_NODES: 'elasticsearch:9200'
      JAVA_OPTS: '-Xms512m -Xmx512m'
    volumes:
      - skywalking-config:/usr/share/logstash/config
      - skywalking-logs:/usr/share/logstash/logs
      - skywalking-message:/var/log/message
    logging:
      driver: 'json-file'
      options:
        max-size: '500m'
        max-file: "10"
    ports:
      - "11800:11800"
      - "12800:12800"
    networks:
      monet_network:
  skywalking-ui:
    restart: always
    privileged: true
    image: registry.cn-beijing.aliyuncs.com/monet/skywalking-ui:9.6.0
    container_name: skywalking-ui
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: http://skywalking-oap:12800
      JAVA_OPTS: '-Xms256m -Xmx256m'
    logging:
      driver: 'json-file'
      options:
        max-size: '500m'
        max-file: "10"
    ports:
      - "18080:8080"
    networks:
      monet_network:
    depends_on:
      - skywalking-oap

