name: Maven 3_6 OpenJDK 17 Docker Workflow

on:
  workflow_dispatch:
  workflow_call:

env:
  DOCKERHUB_IMAGE: fakebilly/maven:3.6-openjdk-17-beta
  GCHR_DOCKERHUB_IMAGE: maven:3.6-openjdk-17-beta
  ALI_DOCKERHUB_IMAGE: monet/maven:3.6-openjdk-17-beta

jobs:
  build:
    name: Maven 3_6 OpenJDK 17 Image Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.0

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: GCHR Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ secrets.GCHR_DOCKERHUB_REGISTRY }}
          username: ${{ secrets.GCHR_DOCKERHUB_USERNAME }}
          password: ${{ secrets.GCHR_DOCKERHUB_TOKEN }}

      - name: Ali Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ secrets.ALI_DOCKERHUB_REGISTRY }}
          username: ${{ secrets.ALI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ALI_DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v5.0.0
        with:
          platforms: |
            linux/amd64
          build-args:
          context: docker-image-maven
          file: docker-image-maven/Dockerfile-3_6-openjdk-17
          no-cache: true
          push: true
          tags: ${{ env.DOCKERHUB_IMAGE }}

      - name: Tag and Push and Remove GCHR Docker Images
        run: |
          docker tag ${{ env.DOCKERHUB_IMAGE }} ${{ secrets.GCHR_DOCKERHUB_REGISTRY }}/${{ secrets.GCHR_DOCKERHUB_USERNAME }}/${{ env.GCHR_DOCKERHUB_IMAGE }}
          docker push ${{ secrets.GCHR_DOCKERHUB_REGISTRY }}/${{ secrets.GCHR_DOCKERHUB_USERNAME }}/${{ env.GCHR_DOCKERHUB_IMAGE }}
          docker rmi ${{ secrets.GCHR_DOCKERHUB_REGISTRY }}/${{ secrets.GCHR_DOCKERHUB_USERNAME }}/${{ env.GCHR_DOCKERHUB_IMAGE }}

      - name: Tag and Push and Remove Ali Docker Images
        run: |
          docker tag ${{ env.DOCKERHUB_IMAGE }} ${{ secrets.ALI_DOCKERHUB_REGISTRY }}/${{ env.ALI_DOCKERHUB_IMAGE }}
          docker push ${{ secrets.ALI_DOCKERHUB_REGISTRY }}/${{ env.ALI_DOCKERHUB_IMAGE }}
          docker rmi ${{ secrets.ALI_DOCKERHUB_REGISTRY }}/${{ env.ALI_DOCKERHUB_IMAGE }}

      - name: Remove Docker Images
        run: |
          docker rmi ${{ env.DOCKERHUB_IMAGE }}
